baseURL = "https://hoochanlon.github.io/hoochanlon/"
defaultContentLanguage = "zh-cn"
theme = "lynx-dev"

title = "Hoochanlon"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[languages]
  [languages.zh-cn]
    locale = "zh-cn"
    languageName = "简体中文"

[params.author]
  name = "Hoochanlon"
  headline = "带砖底层劳工/内容生产者"
  image = "img/author.jpg"  # 使用头像

  links = [
#   { link = { href = "/styles/", text = "链接样式展示", target = "_self" } },
    { github = { href = "https://github.com/hoochanlon", text = "github", target = "_self" }},
    { email = { href = "mailto:hoochanlon@outlok.com", text = "email", target = "_self" }},
    { crt = { href = "/hcl/index.html", text = "CRT Style", target = "_self" } },
    { google = { href = "https://google.com", text = "google", target = "_self" }},
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
