baseURL = "https://hoochanlon.github.io/hoochanlon/"
defaultContentLanguage = "zh-cn"
theme = "lynx-dev"

title = "Chanlon Hoo"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[languages]
  [languages.zh-cn]
    locale = "zh-cn"
    languageName = "简体中文"

[params.author]
  name = "Chanlon Hoo"
  headline = "开发者 & 极客"
  image = "img/author.jpg"  # 使用头像

  links = [
    { crt = { href = "/hcl/index.html", text = "🖥️ CRT Terminal", target = "_self" } },
    { link = { href = "/styles/", text = "📋 链接样式展示", target = "_self" } },
    { github = "https://github.com/hoochanlon"},
    { email = "mailto:hoochanlon@outlok.com"},
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
